// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VysyxSoCFull.h for the primary calling header

#ifndef VERILATED_VYSYXSOCFULL_AXI4USERYANKER_1_H_
#define VERILATED_VYSYXSOCFULL_AXI4USERYANKER_1_H_  // guard

#include "verilated.h"

class VysyxSoCFull__Syms;

class VysyxSoCFull_AXI4UserYanker_1 final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        VL_OUT8(auto_in_awready,0,0);
        VL_IN8(auto_in_awvalid,0,0);
        VL_IN8(auto_in_awid,3,0);
        VL_IN8(auto_in_awlen,7,0);
        VL_IN8(auto_in_awsize,2,0);
        VL_IN8(auto_in_awburst,1,0);
        VL_IN8(auto_in_awecho_tl_state_size,3,0);
        VL_IN8(auto_in_awecho_tl_state_source,6,0);
        VL_IN8(auto_in_awecho_extra_id,0,0);
        VL_OUT8(auto_in_wready,0,0);
        VL_IN8(auto_in_wvalid,0,0);
        VL_IN8(auto_in_wstrb,3,0);
        VL_IN8(auto_in_wlast,0,0);
        VL_IN8(auto_in_bready,0,0);
        VL_OUT8(auto_in_bvalid,0,0);
        VL_OUT8(auto_in_bid,3,0);
        VL_OUT8(auto_in_bresp,1,0);
        VL_OUT8(auto_in_becho_tl_state_size,3,0);
        VL_OUT8(auto_in_becho_tl_state_source,6,0);
        VL_OUT8(auto_in_becho_extra_id,0,0);
        VL_OUT8(auto_in_arready,0,0);
        VL_IN8(auto_in_arvalid,0,0);
        VL_IN8(auto_in_arid,3,0);
        VL_IN8(auto_in_arlen,7,0);
        VL_IN8(auto_in_arsize,2,0);
        VL_IN8(auto_in_arburst,1,0);
        VL_IN8(auto_in_arecho_tl_state_size,3,0);
        VL_IN8(auto_in_arecho_tl_state_source,6,0);
        VL_IN8(auto_in_arecho_extra_id,0,0);
        VL_IN8(auto_in_rready,0,0);
        VL_OUT8(auto_in_rvalid,0,0);
        VL_OUT8(auto_in_rid,3,0);
        VL_OUT8(auto_in_rresp,1,0);
        VL_OUT8(auto_in_recho_tl_state_size,3,0);
        VL_OUT8(auto_in_recho_tl_state_source,6,0);
        VL_OUT8(auto_in_recho_extra_id,0,0);
        VL_OUT8(auto_in_rlast,0,0);
        VL_IN8(auto_out_awready,0,0);
        VL_OUT8(auto_out_awvalid,0,0);
        VL_OUT8(auto_out_awid,3,0);
        VL_OUT8(auto_out_awlen,7,0);
        VL_OUT8(auto_out_awsize,2,0);
        VL_OUT8(auto_out_awburst,1,0);
        VL_IN8(auto_out_wready,0,0);
        VL_OUT8(auto_out_wvalid,0,0);
        VL_OUT8(auto_out_wstrb,3,0);
        VL_OUT8(auto_out_wlast,0,0);
        VL_OUT8(auto_out_bready,0,0);
        VL_IN8(auto_out_bvalid,0,0);
        VL_IN8(auto_out_bid,3,0);
        VL_IN8(auto_out_bresp,1,0);
        VL_IN8(auto_out_arready,0,0);
        VL_OUT8(auto_out_arvalid,0,0);
        VL_OUT8(auto_out_arid,3,0);
        VL_OUT8(auto_out_arlen,7,0);
        VL_OUT8(auto_out_arsize,2,0);
        VL_OUT8(auto_out_arburst,1,0);
        VL_OUT8(auto_out_rready,0,0);
        VL_IN8(auto_out_rvalid,0,0);
        VL_IN8(auto_out_rid,3,0);
        VL_IN8(auto_out_rresp,1,0);
        VL_IN8(auto_out_rlast,0,0);
    };
    struct {
        CData/*0:0*/ __PVT___GEN_3;
        CData/*0:0*/ __PVT___GEN_4;
        CData/*0:0*/ __PVT___GEN_11;
        CData/*0:0*/ __PVT___GEN_12;
        CData/*0:0*/ __VdfgTmp_h3deb4dd1__0;
        CData/*0:0*/ __VdfgTmp_h6bd82316__0;
        CData/*4:0*/ __PVT__Queue17_BundleMap__DOT__enq_ptr_value;
        CData/*4:0*/ __PVT__Queue17_BundleMap__DOT__deq_ptr_value;
        CData/*0:0*/ __PVT__Queue17_BundleMap__DOT__maybe_full;
        CData/*0:0*/ __PVT__Queue17_BundleMap__DOT__ptr_match;
        CData/*0:0*/ __PVT__Queue17_BundleMap__DOT__empty;
        CData/*0:0*/ __PVT__Queue17_BundleMap__DOT__full;
        CData/*0:0*/ __PVT__Queue17_BundleMap__DOT__do_enq;
        CData/*0:0*/ __PVT__Queue17_BundleMap__DOT__unnamedblk1__DOT__do_deq;
        CData/*4:0*/ __PVT__Queue17_BundleMap_1__DOT__enq_ptr_value;
        CData/*4:0*/ __PVT__Queue17_BundleMap_1__DOT__deq_ptr_value;
        CData/*0:0*/ __PVT__Queue17_BundleMap_1__DOT__maybe_full;
        CData/*0:0*/ __PVT__Queue17_BundleMap_1__DOT__ptr_match;
        CData/*0:0*/ __PVT__Queue17_BundleMap_1__DOT__empty;
        CData/*0:0*/ __PVT__Queue17_BundleMap_1__DOT__full;
        CData/*0:0*/ __PVT__Queue17_BundleMap_1__DOT__do_enq;
        CData/*0:0*/ __PVT__Queue17_BundleMap_1__DOT__unnamedblk1__DOT__do_deq;
        CData/*4:0*/ __PVT__Queue17_BundleMap_2__DOT__enq_ptr_value;
        CData/*4:0*/ __PVT__Queue17_BundleMap_2__DOT__deq_ptr_value;
        CData/*0:0*/ __PVT__Queue17_BundleMap_2__DOT__maybe_full;
        CData/*0:0*/ __PVT__Queue17_BundleMap_2__DOT__ptr_match;
        CData/*0:0*/ __PVT__Queue17_BundleMap_2__DOT__empty;
        CData/*0:0*/ __PVT__Queue17_BundleMap_2__DOT__full;
        CData/*0:0*/ __PVT__Queue17_BundleMap_2__DOT__do_enq;
        CData/*0:0*/ __PVT__Queue17_BundleMap_2__DOT__unnamedblk1__DOT__do_deq;
        CData/*4:0*/ __PVT__Queue17_BundleMap_3__DOT__enq_ptr_value;
        CData/*4:0*/ __PVT__Queue17_BundleMap_3__DOT__deq_ptr_value;
        CData/*0:0*/ __PVT__Queue17_BundleMap_3__DOT__maybe_full;
        CData/*0:0*/ __PVT__Queue17_BundleMap_3__DOT__ptr_match;
        CData/*0:0*/ __PVT__Queue17_BundleMap_3__DOT__empty;
        CData/*0:0*/ __PVT__Queue17_BundleMap_3__DOT__full;
        CData/*0:0*/ __PVT__Queue17_BundleMap_3__DOT__do_enq;
        CData/*0:0*/ __PVT__Queue17_BundleMap_3__DOT__unnamedblk1__DOT__do_deq;
        CData/*4:0*/ __PVT__Queue17_BundleMap_4__DOT__enq_ptr_value;
        CData/*4:0*/ __PVT__Queue17_BundleMap_4__DOT__deq_ptr_value;
        CData/*0:0*/ __PVT__Queue17_BundleMap_4__DOT__maybe_full;
        CData/*0:0*/ __PVT__Queue17_BundleMap_4__DOT__ptr_match;
        CData/*0:0*/ __PVT__Queue17_BundleMap_4__DOT__empty;
        CData/*0:0*/ __PVT__Queue17_BundleMap_4__DOT__full;
        CData/*0:0*/ __PVT__Queue17_BundleMap_4__DOT__do_enq;
        CData/*0:0*/ __PVT__Queue17_BundleMap_4__DOT__unnamedblk1__DOT__do_deq;
        CData/*4:0*/ __PVT__Queue17_BundleMap_5__DOT__enq_ptr_value;
        CData/*4:0*/ __PVT__Queue17_BundleMap_5__DOT__deq_ptr_value;
        CData/*0:0*/ __PVT__Queue17_BundleMap_5__DOT__maybe_full;
        CData/*0:0*/ __PVT__Queue17_BundleMap_5__DOT__ptr_match;
        CData/*0:0*/ __PVT__Queue17_BundleMap_5__DOT__empty;
        CData/*0:0*/ __PVT__Queue17_BundleMap_5__DOT__full;
        CData/*0:0*/ __PVT__Queue17_BundleMap_5__DOT__do_enq;
        CData/*0:0*/ __PVT__Queue17_BundleMap_5__DOT__unnamedblk1__DOT__do_deq;
        CData/*4:0*/ __PVT__Queue17_BundleMap_6__DOT__enq_ptr_value;
        CData/*4:0*/ __PVT__Queue17_BundleMap_6__DOT__deq_ptr_value;
        CData/*0:0*/ __PVT__Queue17_BundleMap_6__DOT__maybe_full;
        CData/*0:0*/ __PVT__Queue17_BundleMap_6__DOT__ptr_match;
        CData/*0:0*/ __PVT__Queue17_BundleMap_6__DOT__empty;
        CData/*0:0*/ __PVT__Queue17_BundleMap_6__DOT__full;
        CData/*0:0*/ __PVT__Queue17_BundleMap_6__DOT__do_enq;
        CData/*0:0*/ __PVT__Queue17_BundleMap_6__DOT__unnamedblk1__DOT__do_deq;
        CData/*0:0*/ __PVT__Queue1_BundleMap__DOT__full;
        CData/*0:0*/ __PVT__Queue1_BundleMap__DOT__unnamedblk1__DOT__do_enq;
    };
    struct {
        CData/*0:0*/ __PVT__Queue1_BundleMap_1__DOT__full;
        CData/*0:0*/ __PVT__Queue1_BundleMap_1__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__Queue1_BundleMap_2__DOT__full;
        CData/*0:0*/ __PVT__Queue1_BundleMap_2__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__Queue1_BundleMap_3__DOT__full;
        CData/*0:0*/ __PVT__Queue1_BundleMap_3__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__Queue1_BundleMap_4__DOT__full;
        CData/*0:0*/ __PVT__Queue1_BundleMap_4__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__Queue1_BundleMap_5__DOT__full;
        CData/*0:0*/ __PVT__Queue1_BundleMap_5__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__Queue1_BundleMap_6__DOT__full;
        CData/*0:0*/ __PVT__Queue1_BundleMap_6__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__Queue1_BundleMap_7__DOT__full;
        CData/*0:0*/ __PVT__Queue1_BundleMap_7__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__Queue1_BundleMap_8__DOT__full;
        CData/*0:0*/ __PVT__Queue1_BundleMap_8__DOT__unnamedblk1__DOT__do_enq;
        CData/*4:0*/ __PVT__Queue17_BundleMap_7__DOT__enq_ptr_value;
        CData/*4:0*/ __PVT__Queue17_BundleMap_7__DOT__deq_ptr_value;
        CData/*0:0*/ __PVT__Queue17_BundleMap_7__DOT__maybe_full;
        CData/*0:0*/ __PVT__Queue17_BundleMap_7__DOT__ptr_match;
        CData/*0:0*/ __PVT__Queue17_BundleMap_7__DOT__empty;
        CData/*0:0*/ __PVT__Queue17_BundleMap_7__DOT__full;
        CData/*0:0*/ __PVT__Queue17_BundleMap_7__DOT__do_enq;
        CData/*0:0*/ __PVT__Queue17_BundleMap_7__DOT__unnamedblk1__DOT__do_deq;
        CData/*4:0*/ __PVT__Queue17_BundleMap_8__DOT__enq_ptr_value;
        CData/*4:0*/ __PVT__Queue17_BundleMap_8__DOT__deq_ptr_value;
        CData/*0:0*/ __PVT__Queue17_BundleMap_8__DOT__maybe_full;
        CData/*0:0*/ __PVT__Queue17_BundleMap_8__DOT__ptr_match;
        CData/*0:0*/ __PVT__Queue17_BundleMap_8__DOT__empty;
        CData/*0:0*/ __PVT__Queue17_BundleMap_8__DOT__full;
        CData/*0:0*/ __PVT__Queue17_BundleMap_8__DOT__do_enq;
        CData/*0:0*/ __PVT__Queue17_BundleMap_8__DOT__unnamedblk1__DOT__do_deq;
        CData/*4:0*/ __PVT__Queue17_BundleMap_9__DOT__enq_ptr_value;
        CData/*4:0*/ __PVT__Queue17_BundleMap_9__DOT__deq_ptr_value;
        CData/*0:0*/ __PVT__Queue17_BundleMap_9__DOT__maybe_full;
        CData/*0:0*/ __PVT__Queue17_BundleMap_9__DOT__ptr_match;
        CData/*0:0*/ __PVT__Queue17_BundleMap_9__DOT__empty;
        CData/*0:0*/ __PVT__Queue17_BundleMap_9__DOT__full;
        CData/*0:0*/ __PVT__Queue17_BundleMap_9__DOT__do_enq;
        CData/*0:0*/ __PVT__Queue17_BundleMap_9__DOT__unnamedblk1__DOT__do_deq;
        CData/*4:0*/ __PVT__Queue17_BundleMap_10__DOT__enq_ptr_value;
        CData/*4:0*/ __PVT__Queue17_BundleMap_10__DOT__deq_ptr_value;
        CData/*0:0*/ __PVT__Queue17_BundleMap_10__DOT__maybe_full;
        CData/*0:0*/ __PVT__Queue17_BundleMap_10__DOT__ptr_match;
        CData/*0:0*/ __PVT__Queue17_BundleMap_10__DOT__empty;
        CData/*0:0*/ __PVT__Queue17_BundleMap_10__DOT__full;
        CData/*0:0*/ __PVT__Queue17_BundleMap_10__DOT__do_enq;
        CData/*0:0*/ __PVT__Queue17_BundleMap_10__DOT__unnamedblk1__DOT__do_deq;
        CData/*4:0*/ __PVT__Queue17_BundleMap_11__DOT__enq_ptr_value;
        CData/*4:0*/ __PVT__Queue17_BundleMap_11__DOT__deq_ptr_value;
        CData/*0:0*/ __PVT__Queue17_BundleMap_11__DOT__maybe_full;
        CData/*0:0*/ __PVT__Queue17_BundleMap_11__DOT__ptr_match;
        CData/*0:0*/ __PVT__Queue17_BundleMap_11__DOT__empty;
        CData/*0:0*/ __PVT__Queue17_BundleMap_11__DOT__full;
        CData/*0:0*/ __PVT__Queue17_BundleMap_11__DOT__do_enq;
        CData/*0:0*/ __PVT__Queue17_BundleMap_11__DOT__unnamedblk1__DOT__do_deq;
        CData/*4:0*/ __PVT__Queue17_BundleMap_12__DOT__enq_ptr_value;
        CData/*4:0*/ __PVT__Queue17_BundleMap_12__DOT__deq_ptr_value;
        CData/*0:0*/ __PVT__Queue17_BundleMap_12__DOT__maybe_full;
        CData/*0:0*/ __PVT__Queue17_BundleMap_12__DOT__ptr_match;
        CData/*0:0*/ __PVT__Queue17_BundleMap_12__DOT__empty;
        CData/*0:0*/ __PVT__Queue17_BundleMap_12__DOT__full;
        CData/*0:0*/ __PVT__Queue17_BundleMap_12__DOT__do_enq;
        CData/*0:0*/ __PVT__Queue17_BundleMap_12__DOT__unnamedblk1__DOT__do_deq;
    };
    struct {
        CData/*4:0*/ __PVT__Queue17_BundleMap_13__DOT__enq_ptr_value;
        CData/*4:0*/ __PVT__Queue17_BundleMap_13__DOT__deq_ptr_value;
        CData/*0:0*/ __PVT__Queue17_BundleMap_13__DOT__maybe_full;
        CData/*0:0*/ __PVT__Queue17_BundleMap_13__DOT__ptr_match;
        CData/*0:0*/ __PVT__Queue17_BundleMap_13__DOT__empty;
        CData/*0:0*/ __PVT__Queue17_BundleMap_13__DOT__full;
        CData/*0:0*/ __PVT__Queue17_BundleMap_13__DOT__do_enq;
        CData/*0:0*/ __PVT__Queue17_BundleMap_13__DOT__unnamedblk1__DOT__do_deq;
        CData/*0:0*/ __PVT__Queue1_BundleMap_9__DOT__full;
        CData/*0:0*/ __PVT__Queue1_BundleMap_9__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__Queue1_BundleMap_10__DOT__full;
        CData/*0:0*/ __PVT__Queue1_BundleMap_10__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__Queue1_BundleMap_11__DOT__full;
        CData/*0:0*/ __PVT__Queue1_BundleMap_11__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__Queue1_BundleMap_12__DOT__full;
        CData/*0:0*/ __PVT__Queue1_BundleMap_12__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__Queue1_BundleMap_13__DOT__full;
        CData/*0:0*/ __PVT__Queue1_BundleMap_13__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__Queue1_BundleMap_14__DOT__full;
        CData/*0:0*/ __PVT__Queue1_BundleMap_14__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__Queue1_BundleMap_15__DOT__full;
        CData/*0:0*/ __PVT__Queue1_BundleMap_15__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__Queue1_BundleMap_16__DOT__full;
        CData/*0:0*/ __PVT__Queue1_BundleMap_16__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__Queue1_BundleMap_17__DOT__full;
        CData/*0:0*/ __PVT__Queue1_BundleMap_17__DOT__unnamedblk1__DOT__do_enq;
        SData/*11:0*/ __PVT__Queue17_BundleMap__DOT___ram_ext_R0_data;
        SData/*11:0*/ Queue17_BundleMap__DOT__ram_ext__DOT____Vlvbound_hdaea10f3__0;
        SData/*11:0*/ __PVT__Queue17_BundleMap_1__DOT___ram_ext_R0_data;
        SData/*11:0*/ Queue17_BundleMap_1__DOT____Vcellinp__ram_ext__W0_data;
        SData/*11:0*/ Queue17_BundleMap_1__DOT__ram_ext__DOT____Vlvbound_hdaea10f3__0;
        SData/*11:0*/ __PVT__Queue17_BundleMap_2__DOT___ram_ext_R0_data;
        SData/*11:0*/ Queue17_BundleMap_2__DOT__ram_ext__DOT____Vlvbound_hdaea10f3__0;
        SData/*11:0*/ __PVT__Queue17_BundleMap_3__DOT___ram_ext_R0_data;
        SData/*11:0*/ Queue17_BundleMap_3__DOT__ram_ext__DOT____Vlvbound_hdaea10f3__0;
        SData/*11:0*/ __PVT__Queue17_BundleMap_4__DOT___ram_ext_R0_data;
        SData/*11:0*/ Queue17_BundleMap_4__DOT__ram_ext__DOT____Vlvbound_hdaea10f3__0;
        SData/*11:0*/ __PVT__Queue17_BundleMap_5__DOT___ram_ext_R0_data;
        SData/*11:0*/ Queue17_BundleMap_5__DOT__ram_ext__DOT____Vlvbound_hdaea10f3__0;
        SData/*11:0*/ __PVT__Queue17_BundleMap_6__DOT___ram_ext_R0_data;
        SData/*11:0*/ Queue17_BundleMap_6__DOT__ram_ext__DOT____Vlvbound_hdaea10f3__0;
        SData/*11:0*/ __PVT__Queue1_BundleMap__DOT__ram;
        SData/*11:0*/ __PVT__Queue1_BundleMap_1__DOT__ram;
        SData/*11:0*/ __PVT__Queue1_BundleMap_2__DOT__ram;
        SData/*11:0*/ __PVT__Queue1_BundleMap_3__DOT__ram;
        SData/*11:0*/ __PVT__Queue1_BundleMap_4__DOT__ram;
        SData/*11:0*/ __PVT__Queue1_BundleMap_5__DOT__ram;
        SData/*11:0*/ __PVT__Queue1_BundleMap_6__DOT__ram;
        SData/*11:0*/ __PVT__Queue1_BundleMap_7__DOT__ram;
        SData/*11:0*/ __PVT__Queue1_BundleMap_8__DOT__ram;
        SData/*11:0*/ __PVT__Queue17_BundleMap_7__DOT___ram_ext_R0_data;
        SData/*11:0*/ Queue17_BundleMap_7__DOT__ram_ext__DOT____Vlvbound_hdaea10f3__0;
        SData/*11:0*/ __PVT__Queue17_BundleMap_8__DOT___ram_ext_R0_data;
        SData/*11:0*/ Queue17_BundleMap_8__DOT__ram_ext__DOT____Vlvbound_hdaea10f3__0;
        SData/*11:0*/ __PVT__Queue17_BundleMap_9__DOT___ram_ext_R0_data;
        SData/*11:0*/ Queue17_BundleMap_9__DOT__ram_ext__DOT____Vlvbound_hdaea10f3__0;
        SData/*11:0*/ __PVT__Queue17_BundleMap_10__DOT___ram_ext_R0_data;
        SData/*11:0*/ Queue17_BundleMap_10__DOT____Vcellinp__ram_ext__W0_data;
        SData/*11:0*/ Queue17_BundleMap_10__DOT__ram_ext__DOT____Vlvbound_hdaea10f3__0;
        SData/*11:0*/ __PVT__Queue17_BundleMap_11__DOT___ram_ext_R0_data;
        SData/*11:0*/ Queue17_BundleMap_11__DOT__ram_ext__DOT____Vlvbound_hdaea10f3__0;
        SData/*11:0*/ __PVT__Queue17_BundleMap_12__DOT___ram_ext_R0_data;
        SData/*11:0*/ Queue17_BundleMap_12__DOT__ram_ext__DOT____Vlvbound_hdaea10f3__0;
        SData/*11:0*/ __PVT__Queue17_BundleMap_13__DOT___ram_ext_R0_data;
    };
    struct {
        SData/*11:0*/ Queue17_BundleMap_13__DOT__ram_ext__DOT____Vlvbound_hdaea10f3__0;
        SData/*11:0*/ __PVT__Queue1_BundleMap_9__DOT__ram;
        SData/*11:0*/ __PVT__Queue1_BundleMap_10__DOT__ram;
        SData/*11:0*/ __PVT__Queue1_BundleMap_11__DOT__ram;
        SData/*11:0*/ __PVT__Queue1_BundleMap_12__DOT__ram;
        SData/*11:0*/ __PVT__Queue1_BundleMap_13__DOT__ram;
        SData/*11:0*/ __PVT__Queue1_BundleMap_14__DOT__ram;
        SData/*11:0*/ __PVT__Queue1_BundleMap_15__DOT__ram;
        SData/*11:0*/ __PVT__Queue1_BundleMap_16__DOT__ram;
        SData/*11:0*/ __PVT__Queue1_BundleMap_17__DOT__ram;
        VL_IN(auto_in_awaddr,31,0);
        VL_IN(auto_in_wdata,31,0);
        VL_IN(auto_in_araddr,31,0);
        VL_OUT(auto_in_rdata,31,0);
        VL_OUT(auto_out_awaddr,31,0);
        VL_OUT(auto_out_wdata,31,0);
        VL_OUT(auto_out_araddr,31,0);
        VL_IN(auto_out_rdata,31,0);
        VlUnpacked<SData/*11:0*/, 17> __PVT__Queue17_BundleMap__DOT__ram_ext__DOT__Memory;
        VlUnpacked<SData/*11:0*/, 17> __PVT__Queue17_BundleMap_1__DOT__ram_ext__DOT__Memory;
        VlUnpacked<SData/*11:0*/, 17> __PVT__Queue17_BundleMap_2__DOT__ram_ext__DOT__Memory;
        VlUnpacked<SData/*11:0*/, 17> __PVT__Queue17_BundleMap_3__DOT__ram_ext__DOT__Memory;
        VlUnpacked<SData/*11:0*/, 17> __PVT__Queue17_BundleMap_4__DOT__ram_ext__DOT__Memory;
        VlUnpacked<SData/*11:0*/, 17> __PVT__Queue17_BundleMap_5__DOT__ram_ext__DOT__Memory;
        VlUnpacked<SData/*11:0*/, 17> __PVT__Queue17_BundleMap_6__DOT__ram_ext__DOT__Memory;
        VlUnpacked<SData/*11:0*/, 17> __PVT__Queue17_BundleMap_7__DOT__ram_ext__DOT__Memory;
        VlUnpacked<SData/*11:0*/, 17> __PVT__Queue17_BundleMap_8__DOT__ram_ext__DOT__Memory;
        VlUnpacked<SData/*11:0*/, 17> __PVT__Queue17_BundleMap_9__DOT__ram_ext__DOT__Memory;
        VlUnpacked<SData/*11:0*/, 17> __PVT__Queue17_BundleMap_10__DOT__ram_ext__DOT__Memory;
        VlUnpacked<SData/*11:0*/, 17> __PVT__Queue17_BundleMap_11__DOT__ram_ext__DOT__Memory;
        VlUnpacked<SData/*11:0*/, 17> __PVT__Queue17_BundleMap_12__DOT__ram_ext__DOT__Memory;
        VlUnpacked<SData/*11:0*/, 17> __PVT__Queue17_BundleMap_13__DOT__ram_ext__DOT__Memory;
    };

    // INTERNAL VARIABLES
    VysyxSoCFull__Syms* const vlSymsp;

    // CONSTRUCTORS
    VysyxSoCFull_AXI4UserYanker_1(VysyxSoCFull__Syms* symsp, const char* v__name);
    ~VysyxSoCFull_AXI4UserYanker_1();
    VL_UNCOPYABLE(VysyxSoCFull_AXI4UserYanker_1);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);


#endif  // guard
